# Generated by Django 4.2.1 on 2023-09-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_colorvariant_alter_product_sizevariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SizeVariant',
            new_name='size_variant',
        ),
    ]
