# Generated by Django 4.2.1 on 2023-09-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ColorVariant',
            new_name='color_variant',
        ),
    ]
